# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DXCCPrefixLookup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(501, 566)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 10, 341, 31))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.formLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelNumberVerifiedText = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNumberVerifiedText.setFont(font)
        self.labelNumberVerifiedText.setObjectName(_fromUtf8("labelNumberVerifiedText"))
        self.horizontalLayout.addWidget(self.labelNumberVerifiedText)
        self.labelNumberVerifiedCount = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNumberVerifiedCount.setFont(font)
        self.labelNumberVerifiedCount.setObjectName(_fromUtf8("labelNumberVerifiedCount"))
        self.horizontalLayout.addWidget(self.labelNumberVerifiedCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 341, 41))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelDXCCPrefixEnter = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelDXCCPrefixEnter.setObjectName(_fromUtf8("labelDXCCPrefixEnter"))
        self.horizontalLayout_2.addWidget(self.labelDXCCPrefixEnter)
        self.lineEditPrefix = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditPrefix.setObjectName(_fromUtf8("lineEditPrefix"))
        self.horizontalLayout_2.addWidget(self.lineEditPrefix)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 150, 461, 31))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelVerifiedAwards = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelVerifiedAwards.setFont(font)
        self.labelVerifiedAwards.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVerifiedAwards.setObjectName(_fromUtf8("labelVerifiedAwards"))
        self.verticalLayout_5.addWidget(self.labelVerifiedAwards)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 190, 411, 80))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox160m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox160m.setObjectName(_fromUtf8("checkBox160m"))
        self.gridLayout_2.addWidget(self.checkBox160m, 2, 3, 1, 1)
        self.checkBox30m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox30m.setObjectName(_fromUtf8("checkBox30m"))
        self.gridLayout_2.addWidget(self.checkBox30m, 1, 4, 1, 1)
        self.checkBox17m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox17m.setObjectName(_fromUtf8("checkBox17m"))
        self.gridLayout_2.addWidget(self.checkBox17m, 1, 2, 1, 1)
        self.checkBox12m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox12m.setObjectName(_fromUtf8("checkBox12m"))
        self.gridLayout_2.addWidget(self.checkBox12m, 0, 4, 1, 1)
        self.checkBox2m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox2m.setObjectName(_fromUtf8("checkBox2m"))
        self.gridLayout_2.addWidget(self.checkBox2m, 0, 1, 1, 1)
        self.checkBox20m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox20m.setObjectName(_fromUtf8("checkBox20m"))
        self.gridLayout_2.addWidget(self.checkBox20m, 1, 3, 1, 1)
        self.checkBox10m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox10m.setObjectName(_fromUtf8("checkBox10m"))
        self.gridLayout_2.addWidget(self.checkBox10m, 0, 3, 1, 1)
        self.checkBox80m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox80m.setObjectName(_fromUtf8("checkBox80m"))
        self.gridLayout_2.addWidget(self.checkBox80m, 2, 2, 1, 1)
        self.checkBox40m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox40m.setObjectName(_fromUtf8("checkBox40m"))
        self.gridLayout_2.addWidget(self.checkBox40m, 2, 1, 1, 1)
        self.checkBox6m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox6m.setObjectName(_fromUtf8("checkBox6m"))
        self.gridLayout_2.addWidget(self.checkBox6m, 0, 2, 1, 1)
        self.checkBox15m = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox15m.setObjectName(_fromUtf8("checkBox15m"))
        self.gridLayout_2.addWidget(self.checkBox15m, 1, 1, 1, 1)
        self.labelBandAwards = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBandAwards.setFont(font)
        self.labelBandAwards.setObjectName(_fromUtf8("labelBandAwards"))
        self.gridLayout_2.addWidget(self.labelBandAwards, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 280, 481, 41))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox5B30mE = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5B30mE.setObjectName(_fromUtf8("checkBox5B30mE"))
        self.gridLayout_4.addWidget(self.checkBox5B30mE, 0, 5, 1, 1)
        self.checkBox5B17mE = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5B17mE.setObjectName(_fromUtf8("checkBox5B17mE"))
        self.gridLayout_4.addWidget(self.checkBox5B17mE, 0, 4, 1, 1)
        self.checkBox5B6mE = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5B6mE.setObjectName(_fromUtf8("checkBox5B6mE"))
        self.gridLayout_4.addWidget(self.checkBox5B6mE, 0, 2, 1, 1)
        self.checkBox5B160mE = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5B160mE.setObjectName(_fromUtf8("checkBox5B160mE"))
        self.gridLayout_4.addWidget(self.checkBox5B160mE, 0, 6, 1, 1)
        self.checkBox5Band = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5Band.setObjectName(_fromUtf8("checkBox5Band"))
        self.gridLayout_4.addWidget(self.checkBox5Band, 0, 1, 1, 1)
        self.label5Band = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label5Band.setFont(font)
        self.label5Band.setObjectName(_fromUtf8("label5Band"))
        self.gridLayout_4.addWidget(self.label5Band, 0, 0, 1, 1)
        self.checkBox5B12mE = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox5B12mE.setObjectName(_fromUtf8("checkBox5B12mE"))
        self.gridLayout_4.addWidget(self.checkBox5B12mE, 0, 3, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(63, 330, 331, 164))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBoxMixedHR = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxMixedHR.setObjectName(_fromUtf8("checkBoxMixedHR"))
        self.gridLayout_5.addWidget(self.checkBoxMixedHR, 0, 2, 1, 1)
        self.checkBoxMixed = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxMixed.setObjectName(_fromUtf8("checkBoxMixed"))
        self.gridLayout_5.addWidget(self.checkBoxMixed, 0, 1, 1, 1)
        self.checkBoxPhone = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxPhone.setObjectName(_fromUtf8("checkBoxPhone"))
        self.gridLayout_5.addWidget(self.checkBoxPhone, 2, 1, 1, 1)
        self.checkBoxSatellite = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxSatellite.setObjectName(_fromUtf8("checkBoxSatellite"))
        self.gridLayout_5.addWidget(self.checkBoxSatellite, 4, 1, 1, 1)
        self.checkBoxDigitalHR = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxDigitalHR.setObjectName(_fromUtf8("checkBoxDigitalHR"))
        self.gridLayout_5.addWidget(self.checkBoxDigitalHR, 3, 2, 1, 1)
        self.checkBoxCW = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxCW.setObjectName(_fromUtf8("checkBoxCW"))
        self.gridLayout_5.addWidget(self.checkBoxCW, 1, 1, 1, 1)
        self.checkBoxCWHR = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxCWHR.setObjectName(_fromUtf8("checkBoxCWHR"))
        self.gridLayout_5.addWidget(self.checkBoxCWHR, 1, 2, 1, 1)
        self.checkBoxPhoneHR = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxPhoneHR.setObjectName(_fromUtf8("checkBoxPhoneHR"))
        self.gridLayout_5.addWidget(self.checkBoxPhoneHR, 2, 2, 1, 1)
        self.checkBoxChallenge = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxChallenge.setObjectName(_fromUtf8("checkBoxChallenge"))
        self.gridLayout_5.addWidget(self.checkBoxChallenge, 5, 1, 1, 1)
        self.checkBoxDigital = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBoxDigital.setObjectName(_fromUtf8("checkBoxDigital"))
        self.gridLayout_5.addWidget(self.checkBoxDigital, 3, 1, 1, 1)
        self.labelModeAwards = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelModeAwards.setFont(font)
        self.labelModeAwards.setObjectName(_fromUtf8("labelModeAwards"))
        self.gridLayout_5.addWidget(self.labelModeAwards, 0, 0, 1, 1)
        self.labelPrefix = QtGui.QLabel(self.centralwidget)
        self.labelPrefix.setGeometry(QtCore.QRect(10, 110, 61, 17))
        self.labelPrefix.setObjectName(_fromUtf8("labelPrefix"))
        self.labelCountry = QtGui.QLabel(self.centralwidget)
        self.labelCountry.setGeometry(QtCore.QRect(80, 110, 301, 17))
        self.labelCountry.setWordWrap(False)
        self.labelCountry.setObjectName(_fromUtf8("labelCountry"))
        self.labelVerified = QtGui.QLabel(self.centralwidget)
        self.labelVerified.setGeometry(QtCore.QRect(390, 110, 81, 17))
        self.labelVerified.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelVerified.setObjectName(_fromUtf8("labelVerified"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ARRL DXCC Awards Verification Prefix Lookup", None))
        self.labelNumberVerifiedText.setText(_translate("MainWindow", "Number of ARRL DXCC entities Imported: ", None))
        self.labelNumberVerifiedCount.setText(_translate("MainWindow", "0", None))
        self.labelDXCCPrefixEnter.setText(_translate("MainWindow", "Enter DXCC Entity Prefix", None))
        self.labelVerifiedAwards.setText(_translate("MainWindow", "Verified Awards Matrix", None))
        self.checkBox160m.setText(_translate("MainWindow", "160m", None))
        self.checkBox30m.setText(_translate("MainWindow", "30m", None))
        self.checkBox17m.setText(_translate("MainWindow", "17m", None))
        self.checkBox12m.setText(_translate("MainWindow", "12m", None))
        self.checkBox2m.setText(_translate("MainWindow", "2m", None))
        self.checkBox20m.setText(_translate("MainWindow", "20m", None))
        self.checkBox10m.setText(_translate("MainWindow", "10m", None))
        self.checkBox80m.setText(_translate("MainWindow", "80m", None))
        self.checkBox40m.setText(_translate("MainWindow", "40m", None))
        self.checkBox6m.setText(_translate("MainWindow", "6m", None))
        self.checkBox15m.setText(_translate("MainWindow", "15m", None))
        self.labelBandAwards.setText(_translate("MainWindow", "Band Awards", None))
        self.checkBox5B30mE.setText(_translate("MainWindow", "30m", None))
        self.checkBox5B17mE.setText(_translate("MainWindow", "17m", None))
        self.checkBox5B6mE.setText(_translate("MainWindow", "6m", None))
        self.checkBox5B160mE.setText(_translate("MainWindow", "160m", None))
        self.checkBox5Band.setText(_translate("MainWindow", "5 Band", None))
        self.label5Band.setText(_translate("MainWindow", "5 Band", None))
        self.checkBox5B12mE.setText(_translate("MainWindow", "12m", None))
        self.checkBoxMixedHR.setText(_translate("MainWindow", "Mixed-HR", None))
        self.checkBoxMixed.setText(_translate("MainWindow", "Mixed", None))
        self.checkBoxPhone.setText(_translate("MainWindow", "Phone", None))
        self.checkBoxSatellite.setText(_translate("MainWindow", "Satellite", None))
        self.checkBoxDigitalHR.setText(_translate("MainWindow", "Digital-HR", None))
        self.checkBoxCW.setText(_translate("MainWindow", "CW", None))
        self.checkBoxCWHR.setText(_translate("MainWindow", "CW-HR", None))
        self.checkBoxPhoneHR.setText(_translate("MainWindow", "Phone-HR", None))
        self.checkBoxChallenge.setText(_translate("MainWindow", "Challenge", None))
        self.checkBoxDigital.setText(_translate("MainWindow", "Digital", None))
        self.labelModeAwards.setText(_translate("MainWindow", "Mode Awards", None))
        self.labelPrefix.setText(_translate("MainWindow", "VP9M", None))
        self.labelCountry.setText(_translate("MainWindow", "United States of America", None))
        self.labelVerified.setText(_translate("MainWindow", "Verified", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

